spring:
  datasource:
    url: jdbc:mysql://localhost:3306/e_commerce_db
    username: root
    password: 199161500318
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect